services:
  - type: web
    name: speedread-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: CORS_ORIGINS
        sync: false
      - key: SECRET_KEY
        generateValue: true
